### ISSUE TITLE
Create code to translate linear representation to change objects

### ISSUE THREAD

**Issue by cmungall** [INCATools/kgcl-tools#3]
Given linear representations of changes such as:

 * Rename foo to bar
 * Move bar from under baz to under fred
 * Obsolete 'bad' with replacement 'new'
 * Merge ‘nerve’ into ‘peripheral nerve’

Translate these into instances of Change objects https://cmungall.github.io/knowledge-graph-change-language/

These changes objects can then be translated into transactions at the owl, rdf, rdf*, or kgx level

The original idea was laid out in this doc:

https://docs.google.com/document/d/1__7p64FOI5ZhiZ6F2TXtUc8JN1XXGwglOiVRrlg9G_c/edit#

This doc outlined a grammar but I think this should instead be derived by reversing the fdocstrings in the datamodel. 

```yaml
  node rename:
    is_a: node change
    description: >-
      A node change where the name (aka rdfs:label) of the node changes
    slots:
      - old value
      - new value
      - has textual diff      
    slot_usage:
      old value:
        multivalued: false
      new value:
        multivalued: false
      change description:
        string_serialization: "rename {about} from {old value} to {new value}"
    examples:
      - value: "rename UBERON:0002398 from 'manus' to 'hand'"
        description: "replacing the rdfs:label of 'manus' on an uberon class with the rdfs:label 'hand'
```
